language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
- cargo build $FEATURES || travis_terminate 1
- cargo test $FEATURES || travis_terminate 1
- if [ "$FEATURES" == "" ]; then ./test.sh; fi

env:
  matrix:
  - FEATURES=--features=lambda --no-default-features
  - FEATURES=
