[package]
name = "dawn"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
nickel = "^0.10"
hyper = "^0.10"
url = "*"
log = "*"
json = "*"
log4rs = {version = ">= 0.5.0", features=["yaml_format"]}
mustache = "*"
itertools = "*"
time = "*"
get_if_addrs = "*"
cookie = "*"
