[package]
name = "dawn"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
actix-web = "0.7"
hyper = "0.12"
url = "*"
log = "*"
json = "*"
log4rs = {version = ">= 0.5.0", features=["yaml_format"]}
mustache = "0.8"
itertools = "*"
time = "*"
get_if_addrs = "*"
cookie = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "*"
reqwest_mock = "0.5"
lazy_static = "1.2"

lambda_http = {optional=true, version="0.1"}
aws_lambda_events = {optional=true, version="^0.2.3"}
reqwest = {optional=true, version="0.9"}

[dev-dependencies]
env_logger = "*"
crossbeam = "0.7"
maplit = "*"

[features]
default = []
lambda = ["lambda_http", "aws_lambda_events", "reqwest"]