[package]
name = "dawn"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
actix-web = "0.7"
hyper = "0.12"
url = "*"
log = "*"
json = "*"
log4rs = {version = ">= 0.5.0", features=["yaml_format"]}
mustache = "0.8"
itertools = "*"
time = "*"
get_if_addrs = "*"
cookie = "*"
serde = "1.0"
serde_derive = "1.0"
reqwest = "0.9"